### ISSUE TITLE
Sync on M1

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/libzkbob-rs#31]

**Comment by AllFi** [comment]
Some refs:
* https://bugs.chromium.org/p/chromium/issues/detail?id=1228686

Some findings:
* The reason why sync on m1 is so slow is that memory allocations and deallocations are extremely slow. 
* There is no simple (or not so simple) way to figure out whether the user uses m1 mac or not in a browser. At least I didn't find one.

We can reduce the number of allocations and deallocation but we can't remove it all because some are necessary.

**Comment by AllFi** [comment]
Without the aforementioned PR-s client's sync on M1 can take more than 10-15 minutes. With these PR-s client's sync takes 10-25 seconds. It is still not as good as it could be but is not terrible either. Btw we could suggest to users on M1 to use Rosetta. Sync with Rosetta takes 5-7 seconds on stage.

**Comment by vadimnikonov1** [comment]
QA review

Google Chrome: All the functionality is OK
FireFox: All the functionality is OK
